---
- hosts: localhost
  vars:
    gather_facts: false

  tasks:
  - name: Simple PUT operation
    aws_s3:
      bucket: ansible-bender-bucket
      object: app
      src: /home/yuhta/Desktop/ansible_bender/simple-test/Prototype/app/nuxt.config.js
      mode: put
